version: "3"

services:
  postgres:
    image: postgres:10.5
    restart: unless-stopped
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - 25600:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  module-base:
    image: module-base:0.0.1
    ports:
    - "25602:25600"
    depends_on:
    - postgres
    environment:
    - OWNER_SERVICE_URL=http://35.226.127.173:25600/
    - POSTGRES_URL=postgres://user:password@postgres:25600/docker-and-k8s
    - CHAT_URL=ws://module-chat:25601/

  module-chat:
    image: module-chat:0.0.1
    ports:
    - "25601:25601"
    depends_on:
    - postgres
