version: "3"

services:
  postgres:
    image: postgres:10.5
    restart: unless-stopped
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
    - 25600:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  # module-base:
  #   image: module-base:0.0.1
  #   ports:
  #     - "25602:25600"
  #   environment:
  #     - OWNER_SERVICE_URL=http://localhost:25600/
  #     - MONGO_URL=mongodb://root:toor@mongo:27017/docker-and-k8s?authSource=admin
  #     - CHAT_URL=ws://module-chat:25601/

  # module-chat:
  #   image: module-chat:0.0.1
  #   ports:
  #     - "25601:25601"
