apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: module-base
  name: module-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-base
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: module-base
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/labproj21/module-base:0.0.1
        imagePullPolicy: Always  #  DEBUG ONLY
        name: module-base
        ports:
        - containerPort: 25600
        resources: {}
        envFrom:
        - configMapRef:
            name: projekt-cm-module-base
status: {}
