apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: module-base
  name: projekt-svc-module-base
spec:
  ports:
  - port: 25600
    protocol: TCP
    name: http
    targetPort: 25600
  selector:
    app: module-base
  type: ClusterIP
status:
  loadBalancer: {}
