apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: module-chat
  name: projekt-svc-module-chat
spec:
  ports:
  - port: 25601
    protocol: TCP
    name: ws
    targetPort: 25601
  selector:
    app: module-chat
  type: ClusterIP
status:
  loadBalancer: {}
